spring:
  config:
    activate:
      on-profile: prod
  datasource:
    source:
      username: root
      password: ${PROD_MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${PROD_MYSQL_URL}:3306/perfume?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    replica:
      username: root
      password: slave
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${PROD_MYSQL_URL}:3307/perfume?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: trace